# Generated by Django 4.0.6 on 2022-07-10 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('transaction_category', models.CharField(choices=[('hou', 'Housing'), ('car', 'Car'), ('gro', 'Groceries'), ('res', 'Restaurants'), ('gas', 'Gas'), ('ent', 'Entertainment'), ('sho', 'Shopping'), ('sub', 'Subscriptions'), ('sav', 'Savings'), ('debt', 'Debt'), ('cha', 'Charity'), ('misc', 'Miscellaneous')], max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_of_transaction', models.DateField(default=django.utils.timezone.now)),
                ('payment_method', models.CharField(choices=[('credit card', 'Credit Card'), ('debit card', 'Debit Card'), ('check', 'Check'), ('cash', 'Cash'), ('income', 'Income')], max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
