# Generated by Django 4.0.6 on 2022-07-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_category',
            field=models.CharField(choices=[('hou', 'Housing'), ('car', 'Car'), ('gro', 'Groceries'), ('res', 'Restaurants'), ('gas', 'Gas'), ('ent', 'Entertainment'), ('sho', 'Shopping'), ('sub', 'Subscriptions'), ('sav', 'Savings'), ('debt', 'Debt'), ('cha', 'Charity'), ('misc', 'Miscellaneous'), ('pay', 'Paycheck')], max_length=255),
        ),
    ]
